from __future__ import annotations

from copy import deepcopy


BUILTIN_PROVIDER_CONFIGS: dict[str, dict] = {
    "codex": {
        "type": "codex",
        "display_name": "Codex CLI / OAuth",
        "enabled": True,
        "auth": "oauth",
        "default_model": "gpt-5.5",
        "models": ["gpt-5.5"],
    },
    "openai": {
        "type": "openai",
        "display_name": "OpenAI API",
        "enabled": False,
        "auth": "api_key",
        "api_key_env": "OPENAI_API_KEY",
        "base_url": "https://api.openai.com/v1",
        "default_model": "gpt-5.1",
        "models": ["gpt-5.1"],
    },
    "openai_api": {
        "type": "openai",
        "display_name": "OpenAI API (legacy id)",
        "enabled": False,
        "auth": "api_key",
        "api_key_env": "OPENAI_API_KEY",
        "base_url": "https://api.openai.com/v1",
        "default_model": "gpt-5.1",
        "models": ["gpt-5.1"],
    },
    "anthropic": {
        "type": "anthropic",
        "display_name": "Anthropic API",
        "enabled": False,
        "auth": "api_key",
        "api_key_env": "ANTHROPIC_API_KEY",
        "base_url": "https://api.anthropic.com",
        "default_model": "claude-sonnet-4-5",
        "models": ["claude-sonnet-4-5"],
    },
    "google": {
        "type": "google",
        "display_name": "Google Gemini API",
        "enabled": False,
        "auth": "api_key",
        "api_key_env": "GEMINI_API_KEY",
        "base_url": "https://generativelanguage.googleapis.com/v1beta",
        "default_model": "gemini-2.5-pro",
        "models": ["gemini-2.5-pro"],
    },
    "gemini": {
        "type": "google",
        "display_name": "Google Gemini API (legacy id)",
        "enabled": False,
        "auth": "api_key",
        "api_key_env": "GEMINI_API_KEY",
        "base_url": "https://generativelanguage.googleapis.com/v1beta",
        "default_model": "gemini-2.5-pro",
        "models": ["gemini-2.5-pro"],
    },
    "vertex": {
        "type": "vertex",
        "display_name": "Google Vertex AI",
        "enabled": False,
        "auth": "api_key",
        "api_key_env": "VERTEX_ACCESS_TOKEN",
        "base_url": "",
        "default_model": "",
        "models": [],
    },
    "openrouter": {
        "type": "openai-compatible",
        "display_name": "OpenRouter",
        "enabled": False,
        "auth": "api_key",
        "api_key_env": "OPENROUTER_API_KEY",
        "base_url": "https://openrouter.ai/api/v1",
        "default_model": "openai/gpt-oss-120b",
        "models": ["openai/gpt-oss-120b"],
    },
    "groq": {
        "type": "openai-compatible",
        "display_name": "Groq",
        "enabled": False,
        "auth": "api_key",
        "api_key_env": "GROQ_API_KEY",
        "base_url": "https://api.groq.com/openai/v1",
        "default_model": "",
        "models": [],
    },
    "mistral": {
        "type": "openai-compatible",
        "display_name": "Mistral API",
        "enabled": False,
        "auth": "api_key",
        "api_key_env": "MISTRAL_API_KEY",
        "base_url": "https://api.mistral.ai/v1",
        "default_model": "",
        "models": [],
    },
    "ollama": {
        "type": "ollama",
        "display_name": "Ollama local",
        "enabled": False,
        "auth": "none",
        "base_url": "http://127.0.0.1:11434",
        "default_model": "llama3.1",
        "models": ["llama3.1"],
    },
    "lmstudio": {
        "type": "openai-compatible",
        "display_name": "LM Studio local",
        "enabled": False,
        "auth": "none",
        "base_url": "http://127.0.0.1:1234/v1",
        "default_model": "",
        "models": [],
        "local": True,
    },
    "deepseek": {
        "type": "openai-compatible",
        "display_name": "DeepSeek API",
        "enabled": False,
        "auth": "api_key",
        "api_key_env": "DEEPSEEK_API_KEY",
        "base_url": "https://api.deepseek.com",
        "default_model": "deepseek-chat",
        "models": ["deepseek-chat"],
    },
    "xai": {
        "type": "openai-compatible",
        "display_name": "xAI API",
        "enabled": False,
        "auth": "api_key",
        "api_key_env": "XAI_API_KEY",
        "base_url": "https://api.x.ai/v1",
        "default_model": "",
        "models": [],
    },
    "custom_openai_compatible": {
        "type": "openai-compatible",
        "display_name": "Custom OpenAI-compatible",
        "enabled": False,
        "auth": "api_key",
        "api_key_env": "CUSTOM_OPENAI_API_KEY",
        "base_url": "",
        "default_model": "",
        "models": [],
    },
}


BUILTIN_PROVIDER_NAMES = frozenset(BUILTIN_PROVIDER_CONFIGS)


def builtin_provider_configs() -> dict[str, dict]:
    return deepcopy(BUILTIN_PROVIDER_CONFIGS)

