from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone

from omega_agent.config import OmegaConfig
from omega_agent.runtime.storage import connect_runtime_db
from omega_agent.security.redaction import is_sensitive_key, redact

PUBLIC_SETTINGS = {
    "provider",
    "model",
    "workspace",
    "host",
    "port",
    "open_browser",
    "safe_mode",
    "require_approvals",
    "workspace_full_access",
    "require_approval_outside_workspace",
    "shell_full_access_in_workspace",
    "allow_delete_in_workspace",
    "allow_git_write_in_workspace",
    "skills_dir",
    "plugins_dir",
    "theme",
    "channels_enabled",
    "webhooks_enabled",
    "telegram_enabled",
    "discord_enabled",
    "scheduler_enabled",
    "scheduler_tick_seconds",
    "reasoning_stream",
    "reasoning_detail",
    "runtime_checkpoints_enabled",
    "runtime_snapshots_enabled",
    "runtime_snapshots_max_file_size_mb",
    "runtime_snapshots_keep_days",
    "runtime_replay_enabled",
    "runtime_resume_interrupted_runs",
    "runtime_max_tool_iterations",
    "runtime_max_actions_per_turn",
    "runtime_max_run_seconds",
    "runtime_dead_letter_enabled",
    "capabilities_enabled",
    "capabilities_max_in_context",
    "capabilities_mcp_enabled",
    "capabilities_a2a_enabled",
    "capabilities_untrusted_disabled_by_default",
    "capabilities_usage_logging",
    "memory_enabled",
    "memory_project_memory_enabled",
    "memory_auto_capture_decisions",
    "memory_auto_capture_tool_lessons",
    "memory_max_context_memories",
    "memory_default_ttl_days",
    "memory_redaction_enabled",
    "memory_require_provenance",
    "memory_compaction_enabled",
    "code_enabled",
    "code_auto_scan",
    "code_test_timeout_seconds",
    "code_max_output_chars",
    "code_allow_npm_install",
    "code_allow_pip_install",
    "code_allow_git_commit",
    "code_allow_git_push",
    "self_healing_enabled",
    "self_healing_max_attempts",
    "self_healing_auto_apply_safe_recoveries",
    "evals_enabled",
    "evals_auto_score_runs",
    "evals_collect_metrics",
    "evals_redact_traces",
    "evals_max_trace_chars",
    "evals_failure_clustering_enabled",
    "evals_default_dataset_dir",
    "evals_report_dir",
    "workflows_enabled",
    "workflows_max_steps",
    "workflows_max_duration_seconds",
    "workflows_allow_nested_workflows",
    "workflows_templates_enabled",
    "workflows_require_approval_for_destructive_steps",
    "connectors_enabled",
    "connectors_openapi_import_enabled",
    "connectors_untrusted_disabled_by_default",
    "connectors_max_response_chars",
    "connectors_timeout_seconds",
    "connectors_github_enabled",
    "connectors_local_http_enabled",
    "connectors_browser_fallback_enabled",
    "events_enabled",
    "events_persist",
    "events_replay_enabled",
    "events_max_replay_events",
    "events_redaction_enabled",
    "events_websocket_heartbeat_seconds",
    "research_enabled",
    "research_max_sources",
    "research_max_claims",
    "research_require_evidence_for_claims",
    "research_export_dir",
    "research_web_enabled",
    "research_external_sources_untrusted",
    "skills_enabled",
    "skills_foundry_enabled",
    "skills_auto_detect_candidates",
    "skills_min_successful_runs_for_candidate",
    "skills_require_user_approval_for_promotion",
    "skills_max_skills_in_context",
    "skills_test_before_activation",
    "governance_budgets_enabled",
    "governance_budgets_default_profile",
    "governance_budgets_enforce",
    "governance_budgets_warning_threshold",
    "governance_risk_governor_enabled",
    "governance_risk_governor_default_max_risk",
    "shadow_enabled",
    "shadow_require_for_high_risk",
    "shadow_require_for_workflows_over_steps",
    "shadow_workspace_keep_days",
    "shadow_max_shadow_seconds",
    "shadow_allow_shell_in_shadow",
    "shadow_auto_promote_low_risk",
    "shadow_compare_after_live",
    "default_model_ref",
    "fallback_model_ref",
    "model_selection_enabled",
    "config_path",
    "config_status",
    "legacy_env_present",
    "model_config_source",
}
PATCHABLE_SETTINGS = {
    "provider",
    "model",
    "open_browser",
    "safe_mode",
    "require_approvals",
    "workspace_full_access",
    "require_approval_outside_workspace",
    "shell_full_access_in_workspace",
    "allow_delete_in_workspace",
    "allow_git_write_in_workspace",
    "theme",
    "default_model_ref",
    "fallback_model_ref",
    "model_selection_enabled",
    "runtime_checkpoints_enabled",
    "runtime_snapshots_enabled",
    "runtime_snapshots_max_file_size_mb",
    "runtime_snapshots_keep_days",
    "runtime_replay_enabled",
    "runtime_resume_interrupted_runs",
    "runtime_max_tool_iterations",
    "runtime_max_actions_per_turn",
    "runtime_max_run_seconds",
    "runtime_dead_letter_enabled",
    "capabilities_enabled",
    "capabilities_max_in_context",
    "capabilities_mcp_enabled",
    "capabilities_a2a_enabled",
    "capabilities_untrusted_disabled_by_default",
    "capabilities_usage_logging",
    "memory_enabled",
    "memory_project_memory_enabled",
    "memory_auto_capture_decisions",
    "memory_auto_capture_tool_lessons",
    "memory_max_context_memories",
    "memory_default_ttl_days",
    "memory_redaction_enabled",
    "memory_require_provenance",
    "memory_compaction_enabled",
    "code_enabled",
    "code_auto_scan",
    "code_test_timeout_seconds",
    "code_max_output_chars",
    "code_allow_npm_install",
    "code_allow_pip_install",
    "code_allow_git_commit",
    "code_allow_git_push",
    "self_healing_enabled",
    "self_healing_max_attempts",
    "self_healing_auto_apply_safe_recoveries",
    "evals_enabled",
    "evals_auto_score_runs",
    "evals_collect_metrics",
    "evals_redact_traces",
    "evals_max_trace_chars",
    "evals_failure_clustering_enabled",
    "evals_default_dataset_dir",
    "evals_report_dir",
    "workflows_enabled",
    "workflows_max_steps",
    "workflows_max_duration_seconds",
    "workflows_allow_nested_workflows",
    "workflows_templates_enabled",
    "workflows_require_approval_for_destructive_steps",
    "connectors_enabled",
    "connectors_openapi_import_enabled",
    "connectors_untrusted_disabled_by_default",
    "connectors_max_response_chars",
    "connectors_timeout_seconds",
    "connectors_github_enabled",
    "connectors_local_http_enabled",
    "connectors_browser_fallback_enabled",
    "events_enabled",
    "events_persist",
    "events_replay_enabled",
    "events_max_replay_events",
    "events_redaction_enabled",
    "events_websocket_heartbeat_seconds",
    "research_enabled",
    "research_max_sources",
    "research_max_claims",
    "research_require_evidence_for_claims",
    "research_export_dir",
    "research_web_enabled",
    "research_external_sources_untrusted",
    "skills_enabled",
    "skills_foundry_enabled",
    "skills_auto_detect_candidates",
    "skills_min_successful_runs_for_candidate",
    "skills_require_user_approval_for_promotion",
    "skills_max_skills_in_context",
    "skills_test_before_activation",
    "governance_budgets_enabled",
    "governance_budgets_default_profile",
    "governance_budgets_enforce",
    "governance_budgets_warning_threshold",
    "governance_risk_governor_enabled",
    "governance_risk_governor_default_max_risk",
    "shadow_enabled",
    "shadow_require_for_high_risk",
    "shadow_require_for_workflows_over_steps",
    "shadow_workspace_keep_days",
    "shadow_max_shadow_seconds",
    "shadow_allow_shell_in_shadow",
    "shadow_auto_promote_low_risk",
    "shadow_compare_after_live",
}


@dataclass(frozen=True)
class SettingsStore:
    config: OmegaConfig

    def get_all(self) -> dict:
        with connect_runtime_db(self.config) as conn:
            rows = conn.execute("SELECT key, value_json FROM settings").fetchall()
        stored = {
            row["key"]: redact(json.loads(row["value_json"]))
            for row in rows
            if row["key"] in PUBLIC_SETTINGS and not is_sensitive_key(row["key"])
        }
        defaults = {
            "provider": self.config.provider,
            "model": self.config.model,
            "workspace": str(self.config.workspace),
            "host": self.config.host,
            "port": self.config.port,
            "open_browser": self.config.open_browser,
            "safe_mode": self.config.safe_mode,
            "require_approvals": self.config.require_approval,
            "workspace_full_access": self.config.workspace_full_access,
            "require_approval_outside_workspace": self.config.require_approval_outside_workspace,
            "shell_full_access_in_workspace": self.config.shell_full_access_in_workspace,
            "allow_delete_in_workspace": self.config.allow_delete_in_workspace,
            "allow_git_write_in_workspace": self.config.allow_git_write_in_workspace,
            "skills_dir": str(self.config.skills_dir),
            "plugins_dir": str(self.config.plugins_dir),
            "theme": self.config.ui_theme,
            "channels_enabled": self.config.channels_enabled,
            "webhooks_enabled": self.config.webhooks_enabled,
            "telegram_enabled": self.config.telegram_enabled,
            "discord_enabled": self.config.discord_enabled,
            "scheduler_enabled": self.config.scheduler_enabled,
            "scheduler_tick_seconds": self.config.scheduler_tick_seconds,
            "reasoning_stream": self.config.reasoning_stream,
            "reasoning_detail": self.config.reasoning_detail,
            "runtime_checkpoints_enabled": self.config.runtime_checkpoints_enabled,
            "runtime_snapshots_enabled": self.config.runtime_snapshots_enabled,
            "runtime_snapshots_max_file_size_mb": self.config.runtime_snapshots_max_file_size_mb,
            "runtime_snapshots_keep_days": self.config.runtime_snapshots_keep_days,
            "runtime_replay_enabled": self.config.runtime_replay_enabled,
            "runtime_resume_interrupted_runs": self.config.runtime_resume_interrupted_runs,
            "runtime_max_tool_iterations": self.config.runtime_max_tool_iterations,
            "runtime_max_actions_per_turn": self.config.runtime_max_actions_per_turn,
            "runtime_max_run_seconds": self.config.runtime_max_run_seconds,
            "runtime_dead_letter_enabled": self.config.runtime_dead_letter_enabled,
            "capabilities_enabled": self.config.capabilities_enabled,
            "capabilities_max_in_context": self.config.capabilities_max_in_context,
            "capabilities_mcp_enabled": self.config.capabilities_mcp_enabled,
            "capabilities_a2a_enabled": self.config.capabilities_a2a_enabled,
            "capabilities_untrusted_disabled_by_default": self.config.capabilities_untrusted_disabled_by_default,
            "capabilities_usage_logging": self.config.capabilities_usage_logging,
            "memory_enabled": self.config.memory_enabled,
            "memory_project_memory_enabled": self.config.memory_project_memory_enabled,
            "memory_auto_capture_decisions": self.config.memory_auto_capture_decisions,
            "memory_auto_capture_tool_lessons": self.config.memory_auto_capture_tool_lessons,
            "memory_max_context_memories": self.config.memory_max_context_memories,
            "memory_default_ttl_days": self.config.memory_default_ttl_days,
            "memory_redaction_enabled": self.config.memory_redaction_enabled,
            "memory_require_provenance": self.config.memory_require_provenance,
            "memory_compaction_enabled": self.config.memory_compaction_enabled,
            "code_enabled": self.config.code_enabled,
            "code_auto_scan": self.config.code_auto_scan,
            "code_test_timeout_seconds": self.config.code_test_timeout_seconds,
            "code_max_output_chars": self.config.code_max_output_chars,
            "code_allow_npm_install": self.config.code_allow_npm_install,
            "code_allow_pip_install": self.config.code_allow_pip_install,
            "code_allow_git_commit": self.config.code_allow_git_commit,
            "code_allow_git_push": self.config.code_allow_git_push,
            "self_healing_enabled": self.config.self_healing_enabled,
            "self_healing_max_attempts": self.config.self_healing_max_attempts,
            "self_healing_auto_apply_safe_recoveries": self.config.self_healing_auto_apply_safe_recoveries,
            "evals_enabled": self.config.evals_enabled,
            "evals_auto_score_runs": self.config.evals_auto_score_runs,
            "evals_collect_metrics": self.config.evals_collect_metrics,
            "evals_redact_traces": self.config.evals_redact_traces,
            "evals_max_trace_chars": self.config.evals_max_trace_chars,
            "evals_failure_clustering_enabled": self.config.evals_failure_clustering_enabled,
            "evals_default_dataset_dir": str(self.config.evals_default_dataset_dir),
            "evals_report_dir": str(self.config.evals_report_dir),
            "workflows_enabled": self.config.workflows_enabled,
            "workflows_max_steps": self.config.workflows_max_steps,
            "workflows_max_duration_seconds": self.config.workflows_max_duration_seconds,
            "workflows_allow_nested_workflows": self.config.workflows_allow_nested_workflows,
            "workflows_templates_enabled": self.config.workflows_templates_enabled,
            "workflows_require_approval_for_destructive_steps": self.config.workflows_require_approval_for_destructive_steps,
            "connectors_enabled": self.config.connectors_enabled,
            "connectors_openapi_import_enabled": self.config.connectors_openapi_import_enabled,
            "connectors_untrusted_disabled_by_default": self.config.connectors_untrusted_disabled_by_default,
            "connectors_max_response_chars": self.config.connectors_max_response_chars,
            "connectors_timeout_seconds": self.config.connectors_timeout_seconds,
            "connectors_github_enabled": self.config.connectors_github_enabled,
            "connectors_local_http_enabled": self.config.connectors_local_http_enabled,
            "connectors_browser_fallback_enabled": self.config.connectors_browser_fallback_enabled,
            "events_enabled": self.config.events_enabled,
            "events_persist": self.config.events_persist,
            "events_replay_enabled": self.config.events_replay_enabled,
            "events_max_replay_events": self.config.events_max_replay_events,
            "events_redaction_enabled": self.config.events_redaction_enabled,
            "events_websocket_heartbeat_seconds": self.config.events_websocket_heartbeat_seconds,
            "research_enabled": self.config.research_enabled,
            "research_max_sources": self.config.research_max_sources,
            "research_max_claims": self.config.research_max_claims,
            "research_require_evidence_for_claims": self.config.research_require_evidence_for_claims,
            "research_export_dir": self.config.research_export_dir,
            "research_web_enabled": self.config.research_web_enabled,
            "research_external_sources_untrusted": self.config.research_external_sources_untrusted,
            "skills_enabled": self.config.skills_enabled,
            "skills_foundry_enabled": self.config.skills_foundry_enabled,
            "skills_auto_detect_candidates": self.config.skills_auto_detect_candidates,
            "skills_min_successful_runs_for_candidate": self.config.skills_min_successful_runs_for_candidate,
            "skills_require_user_approval_for_promotion": self.config.skills_require_user_approval_for_promotion,
            "skills_max_skills_in_context": self.config.skills_max_skills_in_context,
            "skills_test_before_activation": self.config.skills_test_before_activation,
            "governance_budgets_enabled": self.config.governance_budgets_enabled,
            "governance_budgets_default_profile": self.config.governance_budgets_default_profile,
            "governance_budgets_enforce": self.config.governance_budgets_enforce,
            "governance_budgets_warning_threshold": self.config.governance_budgets_warning_threshold,
            "governance_risk_governor_enabled": self.config.governance_risk_governor_enabled,
            "governance_risk_governor_default_max_risk": self.config.governance_risk_governor_default_max_risk,
            "shadow_enabled": self.config.shadow_enabled,
            "shadow_require_for_high_risk": self.config.shadow_require_for_high_risk,
            "shadow_require_for_workflows_over_steps": self.config.shadow_require_for_workflows_over_steps,
            "shadow_workspace_keep_days": self.config.shadow_workspace_keep_days,
            "shadow_max_shadow_seconds": self.config.shadow_max_shadow_seconds,
            "shadow_allow_shell_in_shadow": self.config.shadow_allow_shell_in_shadow,
            "shadow_auto_promote_low_risk": self.config.shadow_auto_promote_low_risk,
            "shadow_compare_after_live": self.config.shadow_compare_after_live,
            "default_model_ref": self.config.default_model_ref,
            "fallback_model_ref": self.config.fallback_model_ref,
            "model_selection_enabled": self.config.model_selection_enabled,
            "config_path": str(self.config.config_path),
            "config_status": self.config.config_status,
            "legacy_env_present": self.config.legacy_env_present,
            "model_config_source": self.config.model_config_source,
        }
        defaults.update(stored)
        return redact(defaults)

    def patch(self, values: dict) -> dict:
        now = datetime.now(timezone.utc).isoformat()
        with connect_runtime_db(self.config) as conn:
            for key, value in values.items():
                if is_sensitive_key(key):
                    raise ValueError(f"Setting sensible refuse: {key}")
                if key not in PATCHABLE_SETTINGS:
                    raise ValueError(f"Setting non modifiable: {key}")
                conn.execute(
                    "INSERT OR REPLACE INTO settings(key, value_json, updated_at) VALUES (?, ?, ?)",
                    (key, json.dumps(value, ensure_ascii=False), now),
                )
        return self.get_all()
